//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssemblyDefender.PE {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AssemblyDefender.PE.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build blob is already attached..
        /// </summary>
        public static string BuildBlobAlreadyAttached {
            get {
                return ResourceManager.GetString("BuildBlobAlreadyAttached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build section is already attached..
        /// </summary>
        public static string BuildSectionAlreadyAttached {
            get {
                return ResourceManager.GetString("BuildSectionAlreadyAttached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build task {0} does not exists..
        /// </summary>
        public static string BuildTaskNotFound {
            get {
                return ResourceManager.GetString("BuildTaskNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to change detached item..
        /// </summary>
        public static string ChangeDetachedNode {
            get {
                return ResourceManager.GetString("ChangeDetachedNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is not a portable executable. DOS header does not contain &apos;MZ&apos; signature..
        /// </summary>
        public static string DOSHeaderSignatureNotValid {
            get {
                return ResourceManager.GetString("DOSHeaderSignatureNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &apos;{0}&apos; does not exists..
        /// </summary>
        public static string FileDoesNotExists {
            get {
                return ResourceManager.GetString("FileDoesNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image source is null..
        /// </summary>
        public static string ImageSourceIsNull {
            get {
                return ResourceManager.GetString("ImageSourceIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PE header does not contain valid signature 0x10b (32-bit) or 0x20b (64-bit)..
        /// </summary>
        public static string PEHeaderSignatureNotValid {
            get {
                return ResourceManager.GetString("PEHeaderSignatureNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is not a portable executable..
        /// </summary>
        public static string PEImageNotValid {
            get {
                return ResourceManager.GetString("PEImageNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PE header does not contain &apos;PE&apos; signature..
        /// </summary>
        public static string PESignatureNotValid {
            get {
                return ResourceManager.GetString("PESignatureNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to resolve image section at RVA {0}..
        /// </summary>
        public static string ResolveImageSectionFailure {
            get {
                return ResourceManager.GetString("ResolveImageSectionFailure", resourceCulture);
            }
        }
    }
}
