//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssemblyDefender.Net {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AssemblyDefender.Net.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicated EntryPoint tokens..
        /// </summary>
        public static string Assembler_DuplicateEntryPoint {
            get {
                return ResourceManager.GetString("Assembler_DuplicateEntryPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly &apos;{0}&apos; could not be loaded..
        /// </summary>
        public static string AssemblyIdentityParseError {
            get {
                return ResourceManager.GetString("AssemblyIdentityParseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly &apos;{0}&apos; could not be loaded..
        /// </summary>
        public static string AssemblyLoadError {
            get {
                return ResourceManager.GetString("AssemblyLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly &apos;{0}&apos; could not be found..
        /// </summary>
        public static string AssemblyNotFound {
            get {
                return ResourceManager.GetString("AssemblyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly reference &apos;{0}&apos; does not exists..
        /// </summary>
        public static string AssemblyReferenceNotFoundByName {
            get {
                return ResourceManager.GetString("AssemblyReferenceNotFoundByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly &apos;{0}&apos; could not be resolved..
        /// </summary>
        public static string AssemblyResolveError {
            get {
                return ResourceManager.GetString("AssemblyResolveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event &apos;{0}&apos; could not be loaded..
        /// </summary>
        public static string EventLoadError {
            get {
                return ResourceManager.GetString("EventLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event &apos;{0}::{1}&apos; could not be found..
        /// </summary>
        public static string EventNotFound {
            get {
                return ResourceManager.GetString("EventNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event &apos;{0}&apos; could not be found..
        /// </summary>
        public static string EventNotFound2 {
            get {
                return ResourceManager.GetString("EventNotFound2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event &apos;{0}&apos; could not be resolved..
        /// </summary>
        public static string EventResolveError {
            get {
                return ResourceManager.GetString("EventResolveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exported type &apos;{0}&apos; could not be resolved..
        /// </summary>
        public static string ExportedTypeResolveError {
            get {
                return ResourceManager.GetString("ExportedTypeResolveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &apos;{0}::{1}&apos; could not be found..
        /// </summary>
        public static string FieldNotFound {
            get {
                return ResourceManager.GetString("FieldNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &apos;{0}&apos; could not be found..
        /// </summary>
        public static string FieldNotFound2 {
            get {
                return ResourceManager.GetString("FieldNotFound2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &apos;{0}&apos; could not be resolved..
        /// </summary>
        public static string FieldResolveError {
            get {
                return ResourceManager.GetString("FieldResolveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &apos;{0}&apos; does not exists..
        /// </summary>
        public static string FileNotExists {
            get {
                return ResourceManager.GetString("FileNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Framework version &apos;{0}&apos; is not valid..
        /// </summary>
        public static string FrameworkVersionNotValid {
            get {
                return ResourceManager.GetString("FrameworkVersionNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate is not valid..
        /// </summary>
        public static string InvalidCertificate {
            get {
                return ResourceManager.GetString("InvalidCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State of assembly is not valid..
        /// </summary>
        public static string InvalidState {
            get {
                return ResourceManager.GetString("InvalidState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record not found on lookup..
        /// </summary>
        public static string LookupRecordNotFound {
            get {
                return ResourceManager.GetString("LookupRecordNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata header does not contain valid signature..
        /// </summary>
        public static string MetadataHeaderNotValid {
            get {
                return ResourceManager.GetString("MetadataHeaderNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &apos;{0}&apos; is not a .NET assembly..
        /// </summary>
        public static string MetadataImageNotValid {
            get {
                return ResourceManager.GetString("MetadataImageNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized metadata stream name &apos;{0}&apos;..
        /// </summary>
        public static string MetadataStreamNameNotValid {
            get {
                return ResourceManager.GetString("MetadataStreamNameNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base method of method &apos;{0}::{1}&apos; could not be found..
        /// </summary>
        public static string MethodBaseNotFound {
            get {
                return ResourceManager.GetString("MethodBaseNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load method body..
        /// </summary>
        public static string MethodBodyBlobNotValid {
            get {
                return ResourceManager.GetString("MethodBodyBlobNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method IL is not valid..
        /// </summary>
        public static string MethodILNotValid {
            get {
                return ResourceManager.GetString("MethodILNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method {0} does not have a valid IL..
        /// </summary>
        public static string MethodILNotValid2 {
            get {
                return ResourceManager.GetString("MethodILNotValid2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method &apos;{0}::{1}&apos; could not be found..
        /// </summary>
        public static string MethodNotFound {
            get {
                return ResourceManager.GetString("MethodNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method &apos;{0}&apos; could not be found..
        /// </summary>
        public static string MethodNotFound2 {
            get {
                return ResourceManager.GetString("MethodNotFound2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid method reference token {0}. Valid token are MemberRef, Method or MethodSpec..
        /// </summary>
        public static string MethodRefTokenNotValid {
            get {
                return ResourceManager.GetString("MethodRefTokenNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method &apos;{0}&apos; could not be resolved..
        /// </summary>
        public static string MethodResolveError {
            get {
                return ResourceManager.GetString("MethodResolveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module &apos;{0}&apos; could not be found..
        /// </summary>
        public static string ModuleNotFound {
            get {
                return ResourceManager.GetString("ModuleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module reference &apos;{0}&apos; does not exists..
        /// </summary>
        public static string ModuleReferenceNotFoundByName {
            get {
                return ResourceManager.GetString("ModuleReferenceNotFoundByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not resolve module &apos;{0}&apos;..
        /// </summary>
        public static string ModuleResolveError {
            get {
                return ResourceManager.GetString("ModuleResolveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method &apos;{0}::{1}&apos; is implemented in native platform-specific code which is not currently supported..
        /// </summary>
        public static string NativeMethodBodyNotSupported {
            get {
                return ResourceManager.GetString("NativeMethodBodyNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prime .NET module is required..
        /// </summary>
        public static string PrimeModuleRequired {
            get {
                return ResourceManager.GetString("PrimeModuleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property {0} and associated method for {1} should be in the same assembly..
        /// </summary>
        public static string PropertyAndMethodNotInTheSameAssembly {
            get {
                return ResourceManager.GetString("PropertyAndMethodNotInTheSameAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load property &apos;{0}&apos;..
        /// </summary>
        public static string PropertyLoadError {
            get {
                return ResourceManager.GetString("PropertyLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &apos;{0}::{1}&apos; could not be found..
        /// </summary>
        public static string PropertyNotFound {
            get {
                return ResourceManager.GetString("PropertyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &apos;{0}&apos; could not be found..
        /// </summary>
        public static string PropertyNotFound2 {
            get {
                return ResourceManager.GetString("PropertyNotFound2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &apos;{0}&apos; could not be resolved..
        /// </summary>
        public static string PropertyResolveError {
            get {
                return ResourceManager.GetString("PropertyResolveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource &apos;{0}&apos; could not be found in assembly &apos;{1}&apos;..
        /// </summary>
        public static string ResourceNotFound {
            get {
                return ResourceManager.GetString("ResourceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource &apos;{0}&apos; could not be found..
        /// </summary>
        public static string ResourceNotFound2 {
            get {
                return ResourceManager.GetString("ResourceNotFound2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource &apos;{0}&apos; could not be resolved..
        /// </summary>
        public static string ResourceResolveError {
            get {
                return ResourceManager.GetString("ResourceResolveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid security attribute signature..
        /// </summary>
        public static string SecurityAttributeSignatureNotValid {
            get {
                return ResourceManager.GetString("SecurityAttributeSignatureNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not deserialize signature..
        /// </summary>
        public static string SignatureDeserializeError {
            get {
                return ResourceManager.GetString("SignatureDeserializeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item with key &apos;{0}&apos; does not exists..
        /// </summary>
        public static string StateItemNotExists {
            get {
                return ResourceManager.GetString("StateItemNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} row {1} does not exists..
        /// </summary>
        public static string TableRowDontExists {
            get {
                return ResourceManager.GetString("TableRowDontExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; could not be loaded..
        /// </summary>
        public static string TypeIdentityParseError {
            get {
                return ResourceManager.GetString("TypeIdentityParseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; could not be found..
        /// </summary>
        public static string TypeNotFound {
            get {
                return ResourceManager.GetString("TypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; could not be resolved..
        /// </summary>
        public static string TypeResolveError {
            get {
                return ResourceManager.GetString("TypeResolveError", resourceCulture);
            }
        }
    }
}
