using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace AssemblyDefender.Baml
{
	internal enum RecordType : byte
	{
		Unknown = 0x0,
		DocumentStart = 0x1,
		DocumentEnd = 0x2,
		ElementStart = 0x3,
		ElementEnd = 0x4,
		Property = 0x5,
		PropertyCustom = 0x6,
		PropertyComplexStart = 0x7,
		PropertyComplexEnd = 0x8,
		PropertyArrayStart = 0x9,
		PropertyArrayEnd = 0xa,
		PropertyIListStart = 0xb,
		PropertyIListEnd = 0xc,
		PropertyIDictionaryStart = 0xd,
		PropertyIDictionaryEnd = 0xe,
		LiteralContent = 0xf,
		Text = 0x10,
		TextWithConverter = 0x11,
		RoutedEvent = 0x12,
		ClrEvent = 0x13,
		XmlnsProperty = 0x14,
		XmlAttribute = 0x15,
		ProcessingInstruction = 0x16,
		Comment = 0x17,
		DefTag = 0x18,
		DefAttribute = 0x19,
		EndAttributes = 0x1a,
		PIMapping = 0x1b,
		AssemblyInfo = 0x1c,
		TypeInfo = 0x1d,
		TypeSerializerInfo = 0x1e,
		AttributeInfo = 0x1f,
		StringInfo = 0x20,
		PropertyStringReference = 0x21,
		PropertyTypeReference = 0x22,
		PropertyWithExtension = 0x23,
		PropertyWithConverter = 0x24,
		DeferableContentStart = 0x25,
		DefAttributeKeyString = 0x26,
		DefAttributeKeyType = 0x27,
		KeyElementStart = 0x28,
		KeyElementEnd = 0x29,
		ConstructorParametersStart = 0x2a,
		ConstructorParametersEnd = 0x2b,
		ConstructorParameterType = 0x2c,
		ConnectionId = 0x2d,
		ContentProperty = 0x2e,
		NamedElementStart = 0x2f,
		StaticResourceStart = 0x30,
		StaticResourceEnd = 0x31,
		StaticResourceId = 0x32,
		TextWithId = 0x33,
		PresentationOptionsAttribute = 0x34,
		LineNumberAndPosition = 0x35,
		LinePosition = 0x36,
		OptimizedStaticResource = 0x37,
		PropertyWithStaticResourceId = 0x38,
		LastRecordType = 0x39,
	}
}
