//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssemblyDefender {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AssemblyDefender.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly &apos;{0}&apos; contains native code..
        /// </summary>
        public static string BuildAssemblyILOnlyError {
            get {
                return ResourceManager.GetString("BuildAssemblyILOnlyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate assembly file &apos;{0}&apos;..
        /// </summary>
        public static string DuplicateAssemblyFile {
            get {
                return ResourceManager.GetString("DuplicateAssemblyFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build log file &apos;{0}&apos; could not be loaded..
        /// </summary>
        public static string LogFileNotValid {
            get {
                return ResourceManager.GetString("LogFileNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build log could not be loaded..
        /// </summary>
        public static string LogNotValid {
            get {
                return ResourceManager.GetString("LogNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate resource &apos;{0}&apos; found in &apos;{1}&apos;.
        /// </summary>
        public static string MergeDuplicatedResource {
            get {
                return ResourceManager.GetString("MergeDuplicatedResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate type &apos;{0}&apos; found in &apos;{1}&apos;.
        /// </summary>
        public static string MergeDuplicatedType {
            get {
                return ResourceManager.GetString("MergeDuplicatedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assemblies with native code are not supported..
        /// </summary>
        public static string NativeCodeErrorHint {
            get {
                return ResourceManager.GetString("NativeCodeErrorHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project file &apos;{0}&apos; could not be loaded..
        /// </summary>
        public static string ProjectFileNotValid {
            get {
                return ResourceManager.GetString("ProjectFileNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project could not be loaded..
        /// </summary>
        public static string ProjectNotValid {
            get {
                return ResourceManager.GetString("ProjectNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure all referenced assemblies are present..
        /// </summary>
        public static string ResolveReferenceErrorHint {
            get {
                return ResourceManager.GetString("ResolveReferenceErrorHint", resourceCulture);
            }
        }
    }
}
