//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssemblyDefender.UI.Model {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AssemblyDefender.UI.Model.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _About Assembly Defender.
        /// </summary>
        public static string AboutMenu {
            get {
                return ResourceManager.GetString("AboutMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Assembly Defender.
        /// </summary>
        public static string AboutWindowCaption {
            get {
                return ResourceManager.GetString("AboutWindowCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate.
        /// </summary>
        public static string Activate {
            get {
                return ResourceManager.GetString("Activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly Defender could not be activated. Please check your internet connection and ensure that a valid serial number has been entered..
        /// </summary>
        public static string ActivationFailed {
            get {
                return ResourceManager.GetString("ActivationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly Defender has been successfully activated..
        /// </summary>
        public static string ActivationSucceed {
            get {
                return ResourceManager.GetString("ActivationSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Activation.
        /// </summary>
        public static string ActivationTitle {
            get {
                return ResourceManager.GetString("ActivationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I want to use the free version.
        /// </summary>
        public static string ActivationTypeFree {
            get {
                return ResourceManager.GetString("ActivationTypeFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline (Manual).
        /// </summary>
        public static string ActivationTypeOffline {
            get {
                return ResourceManager.GetString("ActivationTypeOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online (Automatic).
        /// </summary>
        public static string ActivationTypeOnline {
            get {
                return ResourceManager.GetString("ActivationTypeOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Assembly.
        /// </summary>
        public static string AddAssembly {
            get {
                return ResourceManager.GetString("AddAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Assembly.
        /// </summary>
        public static string AddAssemblyMenu {
            get {
                return ResourceManager.GetString("AddAssemblyMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Assembly (Ctrl+Shift+N).
        /// </summary>
        public static string AddAssemblyToolTip {
            get {
                return ResourceManager.GetString("AddAssemblyToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alt+F4.
        /// </summary>
        public static string AltF4 {
            get {
                return ResourceManager.GetString("AltF4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alt+Left.
        /// </summary>
        public static string AltLeft {
            get {
                return ResourceManager.GetString("AltLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alt+Right.
        /// </summary>
        public static string AltRight {
            get {
                return ResourceManager.GetString("AltRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask a question.
        /// </summary>
        public static string AskQuestion {
            get {
                return ResourceManager.GetString("AskQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove assembly {0} ?.
        /// </summary>
        public static string AskRemoveAssembly {
            get {
                return ResourceManager.GetString("AskRemoveAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save changes ?.
        /// </summary>
        public static string AskSaveChanges {
            get {
                return ResourceManager.GetString("AskSaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assemblies.
        /// </summary>
        public static string Assemblies {
            get {
                return ResourceManager.GetString("Assemblies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly.
        /// </summary>
        public static string Assembly {
            get {
                return ResourceManager.GetString("Assembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly &apos;{0}&apos; already exists..
        /// </summary>
        public static string AssemblyFileDuplicate {
            get {
                return ResourceManager.GetString("AssemblyFileDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &apos;{0}&apos; does not contain an assembly manifest..
        /// </summary>
        public static string AssemblyFileNotValid {
            get {
                return ResourceManager.GetString("AssemblyFileNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid assembly file name. A file cannot contain any of the following characters: /\:*?&quot;&lt;&gt;|.
        /// </summary>
        public static string AssemblyNameNotValid {
            get {
                return ResourceManager.GetString("AssemblyNameNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly file {0} contains unmanaged code which is not supported by Assembly Defender..
        /// </summary>
        public static string AssemblyUnmanagedNotSupported {
            get {
                return ResourceManager.GetString("AssemblyUnmanagedNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build.
        /// </summary>
        public static string Build {
            get {
                return ResourceManager.GetString("Build", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project build failed.
        /// </summary>
        public static string BuildErrorTitle {
            get {
                return ResourceManager.GetString("BuildErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build Error.
        /// </summary>
        public static string BuildErrorWindowCaption {
            get {
                return ResourceManager.GetString("BuildErrorWindowCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build Project.
        /// </summary>
        public static string BuildProject {
            get {
                return ResourceManager.GetString("BuildProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Build Project.
        /// </summary>
        public static string BuildProjectMenu {
            get {
                return ResourceManager.GetString("BuildProjectMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build Project (F5).
        /// </summary>
        public static string BuildProjectToolTip {
            get {
                return ResourceManager.GetString("BuildProjectToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build completed successfully.
        /// </summary>
        public static string BuildStatusCompleted {
            get {
                return ResourceManager.GetString("BuildStatusCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build in progress....
        /// </summary>
        public static string BuildStatusInProgress {
            get {
                return ResourceManager.GetString("BuildStatusInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping....
        /// </summary>
        public static string BuildStatusStopping {
            get {
                return ResourceManager.GetString("BuildStatusStopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Build Project.
        /// </summary>
        public static string BuildWindowCaption {
            get {
                return ResourceManager.GetString("BuildWindowCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New.
        /// </summary>
        public static string ButtonAddNew {
            get {
                return ResourceManager.GetString("ButtonAddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove All.
        /// </summary>
        public static string ButtonRemoveAll {
            get {
                return ResourceManager.GetString("ButtonRemoveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change assembly location.
        /// </summary>
        public static string ChangeInputPath {
            get {
                return ResourceManager.GetString("ChangeInputPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change output path.
        /// </summary>
        public static string ChangeOutputPath {
            get {
                return ResourceManager.GetString("ChangeOutputPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Clean.
        /// </summary>
        public static string CleanBuildMenu {
            get {
                return ResourceManager.GetString("CleanBuildMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear All.
        /// </summary>
        public static string ClearAll {
            get {
                return ResourceManager.GetString("ClearAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Clear List).
        /// </summary>
        public static string ClearListBrace {
            get {
                return ResourceManager.GetString("ClearListBrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse All.
        /// </summary>
        public static string CollapseAll {
            get {
                return ResourceManager.GetString("CollapseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company:.
        /// </summary>
        public static string CompanyLabel {
            get {
                return ResourceManager.GetString("CompanyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compress.
        /// </summary>
        public static string Compress {
            get {
                return ResourceManager.GetString("Compress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+F.
        /// </summary>
        public static string ControlF {
            get {
                return ResourceManager.GetString("ControlF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+N.
        /// </summary>
        public static string ControlN {
            get {
                return ResourceManager.GetString("ControlN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+O.
        /// </summary>
        public static string ControlO {
            get {
                return ResourceManager.GetString("ControlO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+S.
        /// </summary>
        public static string ControlS {
            get {
                return ResourceManager.GetString("ControlS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+Shift+N.
        /// </summary>
        public static string ControlShiftN {
            get {
                return ResourceManager.GetString("ControlShiftN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright:.
        /// </summary>
        public static string CopyrightLabel {
            get {
                return ResourceManager.GetString("CopyrightLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © 2019 Nikolay Andreev. All rights reserved..
        /// </summary>
        public static string CopyrightReserved {
            get {
                return ResourceManager.GetString("CopyrightReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Culture:.
        /// </summary>
        public static string CultureLabel {
            get {
                return ResourceManager.GetString("CultureLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decode.
        /// </summary>
        public static string Decode {
            get {
                return ResourceManager.GetString("Decode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decode Stack Trace.
        /// </summary>
        public static string DecodeStackTrace {
            get {
                return ResourceManager.GetString("DecodeStackTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly Defender.
        /// </summary>
        public static string DefaultWindowCaption {
            get {
                return ResourceManager.GetString("DefaultWindowCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Del.
        /// </summary>
        public static string Del {
            get {
                return ResourceManager.GetString("Del", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        public static string DescriptionLabel {
            get {
                return ResourceManager.GetString("DescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devirtualize method.
        /// </summary>
        public static string DevirtualizeMethod {
            get {
                return ResourceManager.GetString("DevirtualizeMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable method devirtualization.
        /// </summary>
        public static string DevirtualizeMethods {
            get {
                return ResourceManager.GetString("DevirtualizeMethods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include public methods.
        /// </summary>
        public static string DevirtualizePublicMethods {
            get {
                return ResourceManager.GetString("DevirtualizePublicMethods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation.
        /// </summary>
        public static string Documentation {
            get {
                return ResourceManager.GetString("Documentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate behavior:.
        /// </summary>
        public static string DuplicateBehaviorLabel {
            get {
                return ResourceManager.GetString("DuplicateBehaviorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Embed assemblies.
        /// </summary>
        public static string EmbedAssemblyCaption {
            get {
                return ResourceManager.GetString("EmbedAssemblyCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An empty string is not allowed..
        /// </summary>
        public static string EmptyStringNotValid {
            get {
                return ResourceManager.GetString("EmptyStringNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypt.
        /// </summary>
        public static string Encrypt {
            get {
                return ResourceManager.GetString("Encrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypt code.
        /// </summary>
        public static string EncryptIL {
            get {
                return ResourceManager.GetString("EncryptIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypt small methods.
        /// </summary>
        public static string EncryptILAtomic {
            get {
                return ResourceManager.GetString("EncryptILAtomic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code encryption.
        /// </summary>
        public static string EncryptILCaption {
            get {
                return ResourceManager.GetString("EncryptILCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any unsaved changes might be lost..
        /// </summary>
        public static string ErrorDescription {
            get {
                return ResourceManager.GetString("ErrorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t Send.
        /// </summary>
        public static string ErrorDontSendButton {
            get {
                return ResourceManager.GetString("ErrorDontSendButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have created an error report that you can send to us. Submitting this report will help us improve Assembly Defender..
        /// </summary>
        public static string ErrorReportDescription {
            get {
                return ResourceManager.GetString("ErrorReportDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide report.
        /// </summary>
        public static string ErrorReportHide {
            get {
                return ResourceManager.GetString("ErrorReportHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show report.
        /// </summary>
        public static string ErrorReportShow {
            get {
                return ResourceManager.GetString("ErrorReportShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please report this problem..
        /// </summary>
        public static string ErrorReportTitle {
            get {
                return ResourceManager.GetString("ErrorReportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Error Report.
        /// </summary>
        public static string ErrorSendButton {
            get {
                return ResourceManager.GetString("ErrorSendButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly Defender has encountered a problem and needs to close..
        /// </summary>
        public static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly Defender Error.
        /// </summary>
        public static string ErrorWindowCaption {
            get {
                return ResourceManager.GetString("ErrorWindowCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event.
        /// </summary>
        public static string Event {
            get {
                return ResourceManager.GetString("Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        public static string Events {
            get {
                return ResourceManager.GetString("Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string EventSemanticAdd {
            get {
                return ResourceManager.GetString("EventSemanticAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoke.
        /// </summary>
        public static string EventSemanticInvoke {
            get {
                return ResourceManager.GetString("EventSemanticInvoke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string EventSemanticRemove {
            get {
                return ResourceManager.GetString("EventSemanticRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E_xit.
        /// </summary>
        public static string ExitMenu {
            get {
                return ResourceManager.GetString("ExitMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand All.
        /// </summary>
        public static string ExpandAll {
            get {
                return ResourceManager.GetString("ExpandAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F1.
        /// </summary>
        public static string F1 {
            get {
                return ResourceManager.GetString("F1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F5.
        /// </summary>
        public static string F5 {
            get {
                return ResourceManager.GetString("F5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAQ.
        /// </summary>
        public static string FAQ {
            get {
                return ResourceManager.GetString("FAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field.
        /// </summary>
        public static string Field {
            get {
                return ResourceManager.GetString("Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find:.
        /// </summary>
        public static string FieldLabel {
            get {
                return ResourceManager.GetString("FieldLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fields.
        /// </summary>
        public static string Fields {
            get {
                return ResourceManager.GetString("Fields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string FileMenu {
            get {
                return ResourceManager.GetString("FileMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forums.
        /// </summary>
        public static string Forums {
            get {
                return ResourceManager.GetString("Forums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward.
        /// </summary>
        public static string Forward {
            get {
                return ResourceManager.GetString("Forward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate unreadable names.
        /// </summary>
        public static string GenerateUnreadableNames {
            get {
                return ResourceManager.GetString("GenerateUnreadableNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Back.
        /// </summary>
        public static string GoBackMenu {
            get {
                return ResourceManager.GetString("GoBackMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back (Alt+Left).
        /// </summary>
        public static string GoBackToolTip {
            get {
                return ResourceManager.GetString("GoBackToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Forward.
        /// </summary>
        public static string GoForwardMenu {
            get {
                return ResourceManager.GetString("GoForwardMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward (Alt+Right).
        /// </summary>
        public static string GoForwardToolTip {
            get {
                return ResourceManager.GetString("GoForwardToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Help.
        /// </summary>
        public static string HelpMenu {
            get {
                return ResourceManager.GetString("HelpMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hint:.
        /// </summary>
        public static string HintLabel {
            get {
                return ResourceManager.GetString("HintLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore ObfuscationAttribute.
        /// </summary>
        public static string IgnoreObfuscationAttribute {
            get {
                return ResourceManager.GetString("IgnoreObfuscationAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inherit.
        /// </summary>
        public static string Inherit {
            get {
                return ResourceManager.GetString("Inherit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inherit All.
        /// </summary>
        public static string InheritAll {
            get {
                return ResourceManager.GetString("InheritAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must be positive or zero..
        /// </summary>
        public static string IntPositiveOrZero {
            get {
                return ResourceManager.GetString("IntPositiveOrZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Knowledge Base.
        /// </summary>
        public static string KnowledgeBase {
            get {
                return ResourceManager.GetString("KnowledgeBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn more....
        /// </summary>
        public static string LearnMore {
            get {
                return ResourceManager.GetString("LearnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine Key:.
        /// </summary>
        public static string MachineKeyLabel {
            get {
                return ResourceManager.GetString("MachineKeyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match case.
        /// </summary>
        public static string MatchCase {
            get {
                return ResourceManager.GetString("MatchCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member.
        /// </summary>
        public static string Member {
            get {
                return ResourceManager.GetString("Member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Members.
        /// </summary>
        public static string Members {
            get {
                return ResourceManager.GetString("Members", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge assemblies.
        /// </summary>
        public static string MergeAssemblyCaption {
            get {
                return ResourceManager.GetString("MergeAssemblyCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method.
        /// </summary>
        public static string Method {
            get {
                return ResourceManager.GetString("Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Methods.
        /// </summary>
        public static string Methods {
            get {
                return ResourceManager.GetString("Methods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module.
        /// </summary>
        public static string Module {
            get {
                return ResourceManager.GetString("Module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge in prime module.
        /// </summary>
        public static string ModuleMergeEnable {
            get {
                return ResourceManager.GetString("ModuleMergeEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modules.
        /// </summary>
        public static string Modules {
            get {
                return ResourceManager.GetString("Modules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More information.
        /// </summary>
        public static string MoreInformation {
            get {
                return ResourceManager.GetString("MoreInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string NameLabel {
            get {
                return ResourceManager.GetString("NameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namespace:.
        /// </summary>
        public static string NamespaceLabel {
            get {
                return ResourceManager.GetString("NamespaceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _New.
        /// </summary>
        public static string NewMenu {
            get {
                return ResourceManager.GetString("NewMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Project.
        /// </summary>
        public static string NewProject {
            get {
                return ResourceManager.GetString("NewProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;New Project&gt;.
        /// </summary>
        public static string NewProjectCaption {
            get {
                return ResourceManager.GetString("NewProjectCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Project (Ctrl+N).
        /// </summary>
        public static string NewToolTip {
            get {
                return ResourceManager.GetString("NewToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obfuscation.
        /// </summary>
        public static string ObfuscateCaption {
            get {
                return ResourceManager.GetString("ObfuscateCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obfuscate control flow.
        /// </summary>
        public static string ObfuscateControlFlow {
            get {
                return ResourceManager.GetString("ObfuscateControlFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypt and compress resources.
        /// </summary>
        public static string ObfuscateResources {
            get {
                return ResourceManager.GetString("ObfuscateResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypt and compress strings.
        /// </summary>
        public static string ObfuscateStrings {
            get {
                return ResourceManager.GetString("ObfuscateStrings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online Help.
        /// </summary>
        public static string OnlineHelp {
            get {
                return ResourceManager.GetString("OnlineHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select File.
        /// </summary>
        public static string OpenFileCaption {
            get {
                return ResourceManager.GetString("OpenFileCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Folder.
        /// </summary>
        public static string OpenFolderCaption {
            get {
                return ResourceManager.GetString("OpenFolderCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in Windows Explorer.
        /// </summary>
        public static string OpenInWindowsExplorer {
            get {
                return ResourceManager.GetString("OpenInWindowsExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Open....
        /// </summary>
        public static string OpenMenu {
            get {
                return ResourceManager.GetString("OpenMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Project.
        /// </summary>
        public static string OpenProject {
            get {
                return ResourceManager.GetString("OpenProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Project File.
        /// </summary>
        public static string OpenProjectFileCaption {
            get {
                return ResourceManager.GetString("OpenProjectFileCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Project (Ctrl+O).
        /// </summary>
        public static string OpenToolTip {
            get {
                return ResourceManager.GetString("OpenToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optimization.
        /// </summary>
        public static string OptimizeCaption {
            get {
                return ResourceManager.GetString("OptimizeCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        public static string Output {
            get {
                return ResourceManager.GetString("Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string PasswordLabel {
            get {
                return ResourceManager.GetString("PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is not valid..
        /// </summary>
        public static string PasswordNotValid {
            get {
                return ResourceManager.GetString("PasswordNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preserve names generated by previous builds.
        /// </summary>
        public static string PreserveNames {
            get {
                return ResourceManager.GetString("PreserveNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Activation.
        /// </summary>
        public static string ProductActivation {
            get {
                return ResourceManager.GetString("ProductActivation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product:.
        /// </summary>
        public static string ProductLabel {
            get {
                return ResourceManager.GetString("ProductLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Support.
        /// </summary>
        public static string ProductSupport {
            get {
                return ResourceManager.GetString("ProductSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add assemblies to protect and optimize.
        /// </summary>
        public static string ProjectEmptyAssemblyHint {
            get {
                return ResourceManager.GetString("ProjectEmptyAssemblyHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can drag &amp; drop assemblies to the navigation panel.
        /// </summary>
        public static string ProjectEmptyDragDropHint {
            get {
                return ResourceManager.GetString("ProjectEmptyDragDropHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Project.
        /// </summary>
        public static string ProjectMenu {
            get {
                return ResourceManager.GetString("ProjectMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        public static string Properties {
            get {
                return ResourceManager.GetString("Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property.
        /// </summary>
        public static string Property {
            get {
                return ResourceManager.GetString("Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getter.
        /// </summary>
        public static string PropertySemanticGet {
            get {
                return ResourceManager.GetString("PropertySemanticGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setter.
        /// </summary>
        public static string PropertySemanticSet {
            get {
                return ResourceManager.GetString("PropertySemanticSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Projects.
        /// </summary>
        public static string RecentProjects {
            get {
                return ResourceManager.GetString("RecentProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Projects.
        /// </summary>
        public static string RecentProjectsMenu {
            get {
                return ResourceManager.GetString("RecentProjectsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string RefreshMenu {
            get {
                return ResourceManager.GetString("RefreshMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Product.
        /// </summary>
        public static string RegisterProduct {
            get {
                return ResourceManager.GetString("RegisterProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Register Product.
        /// </summary>
        public static string RegisterProductMenu {
            get {
                return ResourceManager.GetString("RegisterProductMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See Also.
        /// </summary>
        public static string RelatedActionCaption {
            get {
                return ResourceManager.GetString("RelatedActionCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove All.
        /// </summary>
        public static string RemoveAll {
            get {
                return ResourceManager.GetString("RemoveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Remove.
        /// </summary>
        public static string RemoveAssemblyMenu {
            get {
                return ResourceManager.GetString("RemoveAssemblyMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Assembly (Del).
        /// </summary>
        public static string RemoveAssemblyToolTip {
            get {
                return ResourceManager.GetString("RemoveAssemblyToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove if not used.
        /// </summary>
        public static string RemoveUnusedMember {
            get {
                return ResourceManager.GetString("RemoveUnusedMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove unused members.
        /// </summary>
        public static string RemoveUnusedMembers {
            get {
                return ResourceManager.GetString("RemoveUnusedMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include public members.
        /// </summary>
        public static string RemoveUnusedPublicMembers {
            get {
                return ResourceManager.GetString("RemoveUnusedPublicMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename bindable members.
        /// </summary>
        public static string RenameBindableMembers {
            get {
                return ResourceManager.GetString("RenameBindableMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename configuration members.
        /// </summary>
        public static string RenameConfigurationMembers {
            get {
                return ResourceManager.GetString("RenameConfigurationMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename configuration types.
        /// </summary>
        public static string RenameConfigurationTypes {
            get {
                return ResourceManager.GetString("RenameConfigurationTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename enum members.
        /// </summary>
        public static string RenameEnumMembers {
            get {
                return ResourceManager.GetString("RenameEnumMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string RenameMember {
            get {
                return ResourceManager.GetString("RenameMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename members.
        /// </summary>
        public static string RenameMembers {
            get {
                return ResourceManager.GetString("RenameMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename public events.
        /// </summary>
        public static string RenamePublicEvents {
            get {
                return ResourceManager.GetString("RenamePublicEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename public fields.
        /// </summary>
        public static string RenamePublicFields {
            get {
                return ResourceManager.GetString("RenamePublicFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename public members.
        /// </summary>
        public static string RenamePublicMembers {
            get {
                return ResourceManager.GetString("RenamePublicMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename public methods.
        /// </summary>
        public static string RenamePublicMethods {
            get {
                return ResourceManager.GetString("RenamePublicMethods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename public properties.
        /// </summary>
        public static string RenamePublicProperties {
            get {
                return ResourceManager.GetString("RenamePublicProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename public types.
        /// </summary>
        public static string RenamePublicTypes {
            get {
                return ResourceManager.GetString("RenamePublicTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename serializable members.
        /// </summary>
        public static string RenameSerializableMembers {
            get {
                return ResourceManager.GetString("RenameSerializableMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename serializable types.
        /// </summary>
        public static string RenameSerializableTypes {
            get {
                return ResourceManager.GetString("RenameSerializableTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources.
        /// </summary>
        public static string Resources {
            get {
                return ResourceManager.GetString("Resources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        public static string Run {
            get {
                return ResourceManager.GetString("Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save _As....
        /// </summary>
        public static string SaveAsMenu {
            get {
                return ResourceManager.GetString("SaveAsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save File As.
        /// </summary>
        public static string SaveFileCaption {
            get {
                return ResourceManager.GetString("SaveFileCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Save.
        /// </summary>
        public static string SaveMenu {
            get {
                return ResourceManager.GetString("SaveMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save (Ctrl+S).
        /// </summary>
        public static string SaveToolTip {
            get {
                return ResourceManager.GetString("SaveToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include public types.
        /// </summary>
        public static string SealPublicTypes {
            get {
                return ResourceManager.GetString("SealPublicTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seal type.
        /// </summary>
        public static string SealType {
            get {
                return ResourceManager.GetString("SealType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable class sealing.
        /// </summary>
        public static string SealTypes {
            get {
                return ResourceManager.GetString("SealTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        public static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial Number:.
        /// </summary>
        public static string SerialNumberLabel {
            get {
                return ResourceManager.GetString("SerialNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Less.
        /// </summary>
        public static string ShowLess {
            get {
                return ResourceManager.GetString("ShowLess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show More.
        /// </summary>
        public static string ShowMore {
            get {
                return ResourceManager.GetString("ShowMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse for strong name key file....
        /// </summary>
        public static string SignBrowseForKeyFile {
            get {
                return ResourceManager.GetString("SignBrowseForKeyFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay sign.
        /// </summary>
        public static string SignDelay {
            get {
                return ResourceManager.GetString("SignDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When delay signed, assembly will not be valid until signed..
        /// </summary>
        public static string SignDelayWarning {
            get {
                return ResourceManager.GetString("SignDelayWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign the assembly.
        /// </summary>
        public static string SignEnable {
            get {
                return ResourceManager.GetString("SignEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign assembly with a Strong Name Key.
        /// </summary>
        public static string SignEnableToolTip {
            get {
                return ResourceManager.GetString("SignEnableToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signing.
        /// </summary>
        public static string Signing {
            get {
                return ResourceManager.GetString("Signing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Page.
        /// </summary>
        public static string StartPage {
            get {
                return ResourceManager.GetString("StartPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strength:.
        /// </summary>
        public static string StrengthLabel {
            get {
                return ResourceManager.GetString("StrengthLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The string is null or empty..
        /// </summary>
        public static string StringNullOrEmpty {
            get {
                return ResourceManager.GetString("StringNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strong name key is encrypted with a password. In order to use this key you must provide the password..
        /// </summary>
        public static string StrongNamePasswordTitle {
            get {
                return ResourceManager.GetString("StrongNamePasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Password.
        /// </summary>
        public static string StrongNamePasswordWindowTitle {
            get {
                return ResourceManager.GetString("StrongNamePasswordWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit Feedback.
        /// </summary>
        public static string SubmitFeedback {
            get {
                return ResourceManager.GetString("SubmitFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppress Microsoft IL Disassembler (ildasm.exe).
        /// </summary>
        public static string SuppressMSIL {
            get {
                return ResourceManager.GetString("SuppressMSIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title:.
        /// </summary>
        public static string TitleLabel {
            get {
                return ResourceManager.GetString("TitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Tools.
        /// </summary>
        public static string ToolsMenu {
            get {
                return ResourceManager.GetString("ToolsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trademark:.
        /// </summary>
        public static string TrademarkLabel {
            get {
                return ResourceManager.GetString("TrademarkLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type:.
        /// </summary>
        public static string TypeLabel {
            get {
                return ResourceManager.GetString("TypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Types.
        /// </summary>
        public static string Types {
            get {
                return ResourceManager.GetString("Types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        public static string Undo {
            get {
                return ResourceManager.GetString("Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unselect All.
        /// </summary>
        public static string UnselectAll {
            get {
                return ResourceManager.GetString("UnselectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        public static string VersionLabel {
            get {
                return ResourceManager.GetString("VersionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Tutorials.
        /// </summary>
        public static string VideoTutorials {
            get {
                return ResourceManager.GetString("VideoTutorials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Build.
        /// </summary>
        public static string ViewBuildMenu {
            get {
                return ResourceManager.GetString("ViewBuildMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build.
        /// </summary>
        public static string ViewBuildToolTip {
            get {
                return ResourceManager.GetString("ViewBuildToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Help.
        /// </summary>
        public static string ViewHelp {
            get {
                return ResourceManager.GetString("ViewHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _View Help.
        /// </summary>
        public static string ViewHelpMenu {
            get {
                return ResourceManager.GetString("ViewHelpMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _View.
        /// </summary>
        public static string ViewMenu {
            get {
                return ResourceManager.GetString("ViewMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property {0}::{1} could not be found..
        /// </summary>
        public static string ViewModelPropertyDoesNotExists {
            get {
                return ResourceManager.GetString("ViewModelPropertyDoesNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Output.
        /// </summary>
        public static string ViewOutputMenu {
            get {
                return ResourceManager.GetString("ViewOutputMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output (Ctrl+O).
        /// </summary>
        public static string ViewOutputToolTip {
            get {
                return ResourceManager.GetString("ViewOutputToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Search.
        /// </summary>
        public static string ViewSearchMenu {
            get {
                return ResourceManager.GetString("ViewSearchMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search (Ctrl+F).
        /// </summary>
        public static string ViewSearchToolTip {
            get {
                return ResourceManager.GetString("ViewSearchToolTip", resourceCulture);
            }
        }
    }
}
