using System;
using System.Collections.Generic;
using System.Text;

namespace AssemblyDefender.Net
{
	public enum MethodCodeTypeFlags : int
	{
		/// <summary>
		/// The default. The method is implemented in common intermediate language (CIL, a.k.a. IL or MSIL).
		/// </summary>
		CIL = 0,

		/// <summary>
		/// The method is implemented in native platform-specific code.
		/// </summary>
		Native = 0x1,

		/// <summary>
		/// The method is implemented in optimized IL. The optimized IL is not supported in existing releases
		/// of the common language runtime, so this flag should not be set.
		/// </summary>
		OptimizedIL = 0x2,

		/// <summary>
		/// The method implementation is automatically generated by the runtime itself.
		/// Only certain methods from the base class library (Mscorlib.dll) carry this flag.
		/// If this flag is set, the RVA of the method must be 0.
		/// </summary>
		Runtime = 0x3,
	}
}
