//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssemblyDefender.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AssemblyDefender.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unicode surrogate characters must be written out as pairs together in the same call, not individually. Consider passing in a character array instead..
        /// </summary>
        public static string Arg_SurrogatesNotAllowedAsSingleChar {
            get {
                return ResourceManager.GetString("Arg_SurrogatesNotAllowedAsSingleChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be null or empty..
        /// </summary>
        public static string ArgumentNullOrEmpty {
            get {
                return ResourceManager.GetString("ArgumentNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blob is not expandable..
        /// </summary>
        public static string BlobNotExpandable {
            get {
                return ResourceManager.GetString("BlobNotExpandable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to read beyond the end of the blob..
        /// </summary>
        public static string BlobReadOutOfBound {
            get {
                return ResourceManager.GetString("BlobReadOutOfBound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blob does not support writing..
        /// </summary>
        public static string BlobWriteNotSupported {
            get {
                return ResourceManager.GetString("BlobWriteNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to write beyond the end of the blob..
        /// </summary>
        public static string BlobWriteOutOfBound {
            get {
                return ResourceManager.GetString("BlobWriteOutOfBound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An item with the same key has already been added..
        /// </summary>
        public static string CollectionAddingDuplicateKey {
            get {
                return ResourceManager.GetString("CollectionAddingDuplicateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option &apos;{0}&apos; is specified more than once..
        /// </summary>
        public static string CommandLineDuplicateOption {
            get {
                return ResourceManager.GetString("CommandLineDuplicateOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value &apos;{1}&apos; for option &apos;{0}&apos;..
        /// </summary>
        public static string CommandLineInvalidValue {
            get {
                return ResourceManager.GetString("CommandLineInvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A value for the &apos;{0}&apos; option is required..
        /// </summary>
        public static string CommandLineMissingOption {
            get {
                return ResourceManager.GetString("CommandLineMissingOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized option: {0}.
        /// </summary>
        public static string CommandLineUnrecognizedOption {
            get {
                return ResourceManager.GetString("CommandLineUnrecognizedOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find directory &apos;{0}&apos;..
        /// </summary>
        public static string DirectoryNotFound {
            get {
                return ResourceManager.GetString("DirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find file &apos;{0}&apos;..
        /// </summary>
        public static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to read 7Bit integer..
        /// </summary>
        public static string Format_Bad7BitInt32 {
            get {
                return ResourceManager.GetString("Format_Bad7BitInt32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An internal error occured. Please contact support to resolve this issue..
        /// </summary>
        public static string InternalError {
            get {
                return ResourceManager.GetString("InternalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PKCS #12 is not valid..
        /// </summary>
        public static string PKCS12NotValid {
            get {
                return ResourceManager.GetString("PKCS12NotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot access a closed Stream..
        /// </summary>
        public static string StreamIsClosed {
            get {
                return ResourceManager.GetString("StreamIsClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream does not support reading..
        /// </summary>
        public static string StreamReadNotSupported {
            get {
                return ResourceManager.GetString("StreamReadNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to read beyond the end of the stream..
        /// </summary>
        public static string StreamReadOutOfBound {
            get {
                return ResourceManager.GetString("StreamReadOutOfBound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream does not support seeking..
        /// </summary>
        public static string StreamSeekNotSupported {
            get {
                return ResourceManager.GetString("StreamSeekNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream is too long..
        /// </summary>
        public static string StreamTooLong {
            get {
                return ResourceManager.GetString("StreamTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream does not support writing..
        /// </summary>
        public static string StreamWriteNotSupported {
            get {
                return ResourceManager.GetString("StreamWriteNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized xml attribute &apos;{0}&apos;..
        /// </summary>
        public static string XmlAttributeNotValid {
            get {
                return ResourceManager.GetString("XmlAttributeNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized xml element &apos;{0}&apos;..
        /// </summary>
        public static string XmlElementNotValid {
            get {
                return ResourceManager.GetString("XmlElementNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xml value &apos;{0}&apos; at node &apos;{1}&apos; is not valid..
        /// </summary>
        public static string XmlNodeValueNotValid {
            get {
                return ResourceManager.GetString("XmlNodeValueNotValid", resourceCulture);
            }
        }
    }
}
